name: emotion
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versioning
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^9.19.1
  permission_handler: ^11.0.1
  http: ^0.13.6
  dio: ^5.0.0
  path_provider: ^2.0.15
  audioplayers: ^6.1.0
  camera: ^0.10.0+2
  url_launcher: ^6.2.4
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^4.0.4
  animated_text_kit: ^4.2.3
  lottie: ^2.2.0
  cached_network_image: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/background_music_wave.jpg
    - assets/music_bg.jpg

    - assets/happy_music.mp3
    - assets/sad_music.mp3
    - assets/neutral_music.mp3


  # To add assets, uncomment and specify files here.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # If using custom fonts, define here.
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
